"""Test HttpConn classes - tools to make http requests."""

import unittest
import json

from ak.conn_http import HttpConn, RequestAdapterAddPathPrefix

from .mock_http import mock_http


#########################
# helpers for testing http requests

class _RequestsTestsMixin:
    # helpers for testing http requests

    def assert_has_header(self, headers, header_name):
        """Assert the header is present in the disctionary.

        The catch here is that headers names are case-insensitive.
        """
        nv = self._get_header_name_val(headers, header_name)
        if nv is None:
            raise AssertionError(f"'{header_name}' not found in {headers}")

    def assert_has_not_header(self, headers, header_name):
        """Assert the header is NOT present in the disctionary.

        The catch here is that headers names are case-insensitive.
        """
        nv = self._get_header_name_val(headers, header_name)
        if nv is not None:
            raise AssertionError(f"'{header_name}' unexpectedly found in {headers}")

    def get_header(self, headers, header_name):
        """header name -> value. Exception if header does not exist."""
        nv = self._get_header_name_val(headers, header_name)
        if nv is None:
            raise AssertionError(f"'{header_name}' not found in {headers}")
        return nv[1]

    def assert_header_value(self, headers, header_name, expected_value, _ignore_case=False):
        """Assert header is present and has expected value."""
        value = self.get_header(headers, header_name)
        if _ignore_case:
            vals_equal = expected_value.lower() == value.lower()
        else:
            vals_equal = expected_value == value
        if not vals_equal:
            raise AssertionError(
                f"Header '{header_name}' value '{value}' != '{expected_value}'")

    def _get_header_name_val(self, headers, header_name):
        # return (header_name, header_value) or None if header not present
        k = header_name.lower()
        for nv in headers.items():
            if k == nv[0].lower():
                return nv
        return None

    def assert_req_ids_unique(self, reqs_ids):
        """Assert the collection of requests id's contains only unique values."""
        unique_reqs_ids = set()
        for req_id in reqs_ids:
            if req_id in unique_reqs_ids:
                raise AssertionError(
                    f"requests ids {x_req_ids} have duplicate '{req_id}'")

    def assert_req_ids_same_sequece(self, reqs_ids):
        """Assert that all the request ids belong to the same sequence.

        Method expects that all the request ids have similar format as generated by
        ak.conn_http.RequestIDGenerator
        """
        val_0, val_1 = self._get_first_ids_from_diff_seq(reqs_ids)
        if val_0 is not None:
            raise AssertionError(
                f"requests ids belong to different sequences: {val_0} {val_1}")

    def _get_first_ids_from_diff_seq(self, reqs_ids):
        # return pair of request ids which belong to different sequences (generated by
        # different RequestIDGenerator objects)
        # Returns (None, None) if all the ids belong to the same sequence
        prefix = reqs_ids[0][:20] if reqs_ids else None
        for val in reqs_ids:
            if val[:20] != prefix:
                return reqs_ids[0], val
        return None, None


class TestHttpConn(unittest.TestCase, _RequestsTestsMixin):
    """Test HttpConn - tool for making http requests."""

    def test_simple_call(self):
        """Test most basic usage scenario."""

        conn = HttpConn("http://omg.com")

        intercepted_requests = []
        with mock_http(intercepted_requests):
            conn.get("some/path", params={"p": 12})
            conn.post("post/path", data={"a": 1})
            conn.put("put/path", data={"a": "bc"})
            conn.delete("del/path")
            conn.patch("patch/path", data={"x": 8})

        self.assertEqual(5, len(intercepted_requests))

        # 1. verify get request
        req = intercepted_requests[0]
        self.assertEqual(req.full_url, "http://omg.com/some/path?p=12")
        self.assert_has_header(req.headers, "X-Request-ID")
        self.assert_has_not_header(req.headers, "Content-Type")

        # 2. verify post request
        req = intercepted_requests[1]
        self.assertEqual(req.full_url, "http://omg.com/post/path")
        self.assert_has_header(req.headers, "X-Request-ID")
        self.assert_has_header(req.headers, "Content-Type")
        self.assert_has_header(req.headers, "CONTENT-TYPE")
        self.assert_has_header(req.headers, "cOnTeNt-tYpE")
        self.assert_header_value(req.headers, "Content-Type", "application/json")

        req_data = json.loads(req.data)
        self.assertEqual(req_data, {"a": 1})

        # 3. verify put request
        req = intercepted_requests[2]
        self.assertEqual(req.full_url, "http://omg.com/put/path")
        self.assert_has_header(req.headers, "X-Request-ID")
        self.assert_header_value(req.headers, "Content-Type", "application/json")

        req_data = json.loads(req.data)
        self.assertEqual(req_data, {"a": "bc"})

        # 4. verify put request
        req = intercepted_requests[3]
        self.assertEqual(req.full_url, "http://omg.com/del/path")
        self.assert_has_header(req.headers, "X-Request-ID")
        self.assert_has_not_header(req.headers, "Content-Type")

        # 5. verify put request
        req = intercepted_requests[4]
        self.assertEqual(req.full_url, "http://omg.com/patch/path")
        self.assert_has_header(req.headers, "X-Request-ID")
        self.assert_header_value(req.headers, "Content-Type", "application/json")

        req_data = json.loads(req.data)
        self.assertEqual(req_data, {"x": 8})

    def test_auth_connections(self):
        """Test connection which Basic Authorization"""

        conn = HttpConn("http://omg.com").set_auth_basic("my_login", "some_password")

        intercepted_requests = []
        with mock_http(intercepted_requests):
            conn.get("some/path")

        req = intercepted_requests[0]
        auth_header = self.get_header(req.headers, "Authorization")
        self.assertTrue(auth_header.startswith(b"Basic "))

        # it is possible to change authorization method for existing connection
        token = "123"
        conn.set_auth_token(token)

        intercepted_requests = []
        with mock_http(intercepted_requests):
            conn.get("some/path")
        req = intercepted_requests[0]

        auth_header = self.get_header(req.headers, "Authorization")
        self.assertTrue(auth_header.startswith("Bearer "))

    def test_extra_headers(self):
        """Test connection with explicitely specified additional headers."""

        conn = HttpConn("http://omg.com").set_auth_basic("my_login", "some_password")

        conn.patch_headers({
            "some-head": "test header value",
        })

        intercepted_requests = []
        with mock_http(intercepted_requests):
            conn.post("some/path", data={"d": 3})
        req = intercepted_requests[0]

        self.assert_has_header(req.headers, "Authorization")
        self.assert_header_value(req.headers, "Content-Type", "application/json")
        self.assert_header_value(req.headers, "sOme-hEAd", "test header value")

    def test_constructors(self):
        """Test various forms of constructor."""

        # 1. Connection created with all
        base_conn = HttpConn(
            "http://omg.com",
            headers={
                "head-one": "value of header one",
                "head-two": "value of header two",
            },
        )

        intercepted_requests = []
        with mock_http(intercepted_requests):
            base_conn.get("some/path")

        req = intercepted_requests[0]
        x_req_ids = [self.get_header(req.headers, "X-Request-ID"), ]

        # 2. connection created based on existing connection
        conn = HttpConn(base_conn)

        intercepted_requests = []
        with mock_http(intercepted_requests):
            conn.get("some/path")
            conn.post("some/path", data={"a": 1})

        req_get = intercepted_requests[0]
        req_post = intercepted_requests[1]

        self.assert_header_value(req_get.headers, "head-one", "value of header one")
        self.assert_header_value(req_post.headers, "head-one", "value of header one")

        # rules of processing of "Content-Type" header are inherited from conn,
        # that means default rules: add the header only if data specified and it is
        # not a string/bytes
        self.assert_has_not_header(req_get.headers, "Content-Type")
        self.assert_has_header(req_post.headers, "Content-Type")

        # by default new HttpConn uses the same generator of request id's
        x_req_ids.append(self.get_header(req_get.headers, "X-Request-ID"))
        x_req_ids.append(self.get_header(req_post.headers, "X-Request-ID"))

        self.assert_req_ids_unique(x_req_ids)
        self.assert_req_ids_same_sequece(x_req_ids)

        # 2. connection created from other connection, some options overridden
        conn_1 = HttpConn(
            base_conn,
            headers={
                "head-one": None,
            },
            request_ids_generator=False,
        )

        # 2.1. creation of a new connection based on base_conn should not affect the base_conn
        intercepted_requests = []
        with mock_http(intercepted_requests):
            base_conn.get("some/path")

        orig_conn_req = intercepted_requests[0]
        x_req_ids.append(self.get_header(orig_conn_req.headers, "X-Request-ID"))

        self.assert_req_ids_unique(x_req_ids)
        self.assert_req_ids_same_sequece(x_req_ids)

        self.assert_header_value(orig_conn_req.headers, "head-one", "value of header one")
        self.assert_header_value(orig_conn_req.headers, "head-two", "value of header two")

        # 2.2. but new connection should have different properties
        intercepted_requests = []
        with mock_http(intercepted_requests):
            conn_1.get("some/path")

        new_conn_req = intercepted_requests[0]
        self.assertEqual(new_conn_req.full_url, "http://omg.com/some/path")

        self.assert_has_not_header(new_conn_req.headers, "head-one")
        self.assert_header_value(new_conn_req.headers, "head-two", "value of header two")

        self.assert_has_not_header(new_conn_req.headers, "X-Request-ID")


class TestHttpRequestAdapters(unittest.TestCase, _RequestsTestsMixin):
    """Test pre-processing request using adapters."""
    # Adapters are not widely used. As of now possiblitity to add prefix
    # to the method path is the only usecase for it.

    def test_adapter(self):
        """Test adapters processing using RequestAdapterAddPathPrefix."""

        conn = HttpConn(
            "http://omg.com", adapters=[RequestAdapterAddPathPrefix("path/prefix"), ])

        intercepted_requests = []
        with mock_http(intercepted_requests):
            conn.get("request/path")

        req = intercepted_requests[0]
        self.assertEqual(req.full_url, "http://omg.com/path/prefixrequest/path")
